export const GENERATE_HIRAGANA_LIST = 'GENERATE_HIRAGANA_LIST';
export const GET_HIRAGANA = 'GET_HIRAGANA';
export const SUBMIT_HIRAGANA = 'SUBMIT_HIRAGANA';
export const QUIT_HIRAGANA = 'QUIT_HIRAGANA';
export const END_HIRAGANA = 'END_HIRAGANA';

export const HIRAGANA_LIST = {
    A: ['あ','い','う','え','お'],
    KA: ['か','き','く','け','こ'],
    SA: ['さ','し','す','せ','そ'],
    TA: ['た','ち','つ','て','と'],
    NA: ['な','に','ぬ','ね','の','ん'],
    HA: ['は','ひ','ふ','へ','ほ'],
    MA: ['ま','み','む','め','も'],
    RA: ['ら','り','る','れ','ろ'],
    YA: ['や','ゆ','よ'],
    WA: ['わ','を'],
    GA: ['が','ぎ','ぐ','げ','ご'],
    ZA: ['ざ','じ','ず','ぜ','ぞ'],
    DA: ['だ','ぢ','づ','で','ど'],
    BA: ['ば','び','ぶ','べ','ぼ'],
    PA: ['ぱ','ぴ','ぷ','ぺ','ぽ'],
    KYA: ['きゃ','きゅ','きょ'],
    SHA: ['しゃ','しゅ','しょ'],
    CHA: ['ちゃ','ちゅ','ちょ'],
    NYA: ['にゃ','にゅ','にょ'],
    HYA: ['ひゃ','ひゅ','ひょ'],
    MYA: ['みゃ','みゅ','みょ'],
    RYA: ['りゃ','りゅ','りょ'],
    GYA: ['ぎゃ','ぎゅ','ぎょ'],
    JA: ['じゃ','じゅ','じょ'],
    DYA: ['ぢゃ','ぢゅ','ぢょ'],
    BYA: ['びゃ','びゅ','びょ'],
    PYA: ['ぴゃ','ぴゅ','ぴょ'],
    VCH1: [
        'わたし', 'あなた', 'かいしゃいん', 'しゃいん', 'しゃちょう', 'ぶちょう', 'かちょう', 'おとこ', 'おんな', 'せんせい',
        'がくせい', 'にほんじん', 'アメリカじん', 'フィリピンじん', 'みんな', 'みなさん', 'ともだち', 'ひと', 'かた',
        'かぞく', 'エンジニア', 'けんしゅうせい', 'かいしゃ', 'オフィス', 'がっこう', 'だいがく', 'うち', 'いえ', 'へや',
        'ちゅうしゃじょう', 'おてあらい', 'コンピュータ', 'パソコン', 'カメラ', 'ノート', 'スリッパ', 
        'くるま', 'ほん', 'くに', 'ことば', 'さん', 'なまえ',
    ],
}

export const ROMAJI = {
    A: ['a','i','u','e','o'],
    KA: ['ka','ki','ku','ke','ko'],
    SA: ['sa','shi','su','se','so'],
    TA: ['ta','chi','tsu','te','to'],
    NA: ['na','ni','nu','ne','no','n'],
    HA: ['ha','hi','fu','he','ho'],
    MA: ['ma','mi','mu','me','mo'],
    RA: ['ra','ri','ru','re','ro'],
    YA: ['ya','yu','yo'],
    WA: ['wa','wo'],
    GA: ['ga','gi','gu','ge','go'],
    ZA: ['za','ji','zu','ze','zo'],
    DA: ['da',['dji', 'dzi', 'ji'],'dzu','de','do'],
    BA: ['ba','bi','bu','be','bo'],
    PA: ['pa','pi','pu','pe','po'],
    KYA: ['kya','kyu','kyo'],
    SHA: ['sha','shu','sho'],
    CHA: ['cha','chu','cho'],
    NYA: ['nya','nyu','nyo'],
    HYA: ['hya','hyu','hyo'],
    MYA: ['mya','myu','myo'],
    RYA: ['rya','ryu','ryo'],
    GYA: ['gya','gyu','gyo'],
    JA: ['ja','ju','jo'],
    DYA: ['dya','dyu','dyo'],
    BYA: ['bya','byu','byo'],
    PYA: ['pya','pyu','pyo'],
    VCH1: [
        'watashi', 'anata', 'kaishain', 'shain', 'shachou', 'buchou', 'kachou', 'otoko', 'onna', 'sensei',
        'gakusei', 'nihonjin', 'amerikajin', 'firipinjin', 'minna', 'minasan', 'tomodachi', 'hito', 'kata',
        'kazoku', 'enjinia', 'kenshuusei', 'kaisha', 'ofisu', 'gakkou', 'daigaku', 'uchi', 'ie', 'heya',
        'chuushajou', 'otearai', 'konpyuuta', 'pasokon', 'kamera', 'nooto', 'surippa', 
        'kuruma', 'hon', 'kuni', 'kotoba', 'san', 'namae',
    ],
}