export const GET_HIRAGANA = 'GET_HIRAGANA';
export const SUBMIT_HIRAGANA = 'SUBMIT_HIRAGANA';
export const QUIT_HIRAGANA = 'QUIT_HIRAGANA';
export const END_HIRAGANA = 'END_HIRAGANA';

export const HIRAGANA_LIST = {
    A: ['あ','い','う','え','お'],
    K: ['か','き','く','け','こ'],
    S: ['さ','し','す','せ','そ'],
    T: ['た','ち','つ','て','と'],
    N: ['な','に','ぬ','ね','の','ん'],
    H: ['は','ひ','ふ','へ','ほ'],
    M: ['ま','み','む','め','も'],
    R: ['ら','り','る','れ','ろ'],
    Y: ['や','ゆ','よ'],
    W: ['わ','を'],
    G: ['が','ぎ','ぐ','げ','ご'],
    Z: ['ざ','じ','ず','ぜ','ぞ'],
    D: ['だ','ぢ','づ','で','ど'],
    B: ['ば','び','ぶ','べ','ぼ'],
    P: ['ぱ','ぴ','ぷ','ぺ','ぽ'],
    KY: ['きゃ','きゅ','きょ'],
    SY: ['しゃ','しゅ','しょ'],
    TY: ['ちゃ','ちゅ','ちょ'],
    NY: ['にゃ','にゅ','にょ'],
    HY: ['ひゃ','ひゅ','ひょ'],
    MY: ['みゃ','みゅ','みょ'],
    RY: ['りゃ','りゅ','りょ'],
    GY: ['ぎゃ','ぎゅ','ぎょ'],
    ZY: ['じゃ','じゅ','じょ'],
    BY: ['びゃ','びゅ','びょ'],
    PY: ['ぴゃ','ぴゅ','ぴょ'],
}

export const ROMAJI = {
    A: ['a','i','u','e','o'],
    K: ['ka','ki','ku','ke','ko'],
    S: ['sa','shi','su','se','so'],
    T: ['ta','chi','tsu','te','to'],
    N: ['na','ni','nu','ne','no','n'],
    H: ['ha','hi','fu','he','ho'],
    M: ['ma','mi','mu','me','mo'],
    R: ['ra','ri','ru','re','ro'],
    Y: ['ya','yu','yo'],
    W: ['wa','wo'],
    G: ['ga','gi','gu','ge','go'],
    Z: ['za','ji','zu','ze','zo'],
    D: ['da',['dji', 'dzi', 'ji'],'dzu','de','do'],
    B: ['ba','bi','bu','be','bo'],
    P: ['pa','pi','pu','pe','po'],
    KY: ['kya','kyu','kyo'],
    SY: ['sha','shu','sho'],
    TY: ['cha','chu','cho'],
    NY: ['nya','nyu','nyo'],
    HY: ['hya','hyu','hyo'],
    MY: ['mya','myu','myo'],
    RY: ['rya','ryu','ryo'],
    GY: ['gya','gyu','gyo'],
    ZY: ['ja','ju','jo'],
    BY: ['bya','byu','byo'],
    PY: ['pya','pyu','pyo'],
}