export const GENERATE_CHARACTER_LIST = 'GENERATE_CHARACTER_LIST';
export const GET_CHARACTER = 'GET_CHARACTER';
export const SUBMIT_CHARACTER = 'SUBMIT_CHARACTER';
export const QUIT_GAME = 'QUIT_GAME';
export const END_GAME = 'END_GAME';

export const QUIZ_LIST = {
    Hiragana: {
        KANA: {
            A: ['あ','い','う','え','お'],
            KA: ['か','き','く','け','こ'],
            SA: ['さ','し','す','せ','そ'],
            TA: ['た','ち','つ','て','と'],
            NA: ['な','に','ぬ','ね','の','ん'],
            HA: ['は','ひ','ふ','へ','ほ'],
            MA: ['ま','み','む','め','も'],
            RA: ['ら','り','る','れ','ろ'],
            YA: ['や','ゆ','よ'],
            WA: ['わ','を'],
            GA: ['が','ぎ','ぐ','げ','ご'],
            ZA: ['ざ','じ','ず','ぜ','ぞ'],
            DA: ['だ','ぢ','づ','で','ど'],
            BA: ['ば','び','ぶ','べ','ぼ'],
            PA: ['ぱ','ぴ','ぷ','ぺ','ぽ'],
            KYA: ['きゃ','きゅ','きょ'],
            SHA: ['しゃ','しゅ','しょ'],
            CHA: ['ちゃ','ちゅ','ちょ'],
            NYA: ['にゃ','にゅ','にょ'],
            HYA: ['ひゃ','ひゅ','ひょ'],
            MYA: ['みゃ','みゅ','みょ'],
            RYA: ['りゃ','りゅ','りょ'],
            GYA: ['ぎゃ','ぎゅ','ぎょ'],
            JA: ['じゃ','じゅ','じょ'],
            DYA: ['ぢゃ','ぢゅ','ぢょ'],
            BYA: ['びゃ','びゅ','びょ'],
            PYA: ['ぴゃ','ぴゅ','ぴょ'],
            VCH1: [
                'わたし', 'あなた', 'かいしゃいん', 'しゃいん', 'しゃちょう', 'ぶちょう', 'かちょう', 'おとこ', 'おんな', 'せんせい',
                'がくせい', 'にほんじん', 'みんな', 'みなさん', 'ともだち', 'ひと', 'かた',
                'かぞく', 'けんしゅうせい', 'かいしゃ', 'がっこう', 'だいがく', 'うち', 'いえ', 'へや',
                'ちゅうしゃじょう', 'おてあらい', 'くるま', 'ほん', 'くに', 'ことば', 'さん', 'なまえ',
            ],
            VCH2: [
                'びょういん', 'こうじょう', 'ぎんこう', 'たいしかん', 'としょかん', 'えいがかん', 'きっさてん', 'ほにゃ', 'かいぎしつ', 
                'りょう', 'えき', 'がいこくじん', 'りょうしん', 'こども', 'こ', 'いぬ', 'ねこ', 'かばん', 'けいたい', 'でんわ', 'かぎ', 
                'めがね', 'とけい', 'つくえ', 'ひきだし', 'いす', 'き',
            ],
        },
        ROMAJI: {
            A: ['a','i','u','e','o'],
            KA: ['ka','ki','ku','ke','ko'],
            SA: ['sa','shi','su','se','so'],
            TA: ['ta','chi','tsu','te','to'],
            NA: ['na','ni','nu','ne','no','n'],
            HA: ['ha','hi','fu','he','ho'],
            MA: ['ma','mi','mu','me','mo'],
            RA: ['ra','ri','ru','re','ro'],
            YA: ['ya','yu','yo'],
            WA: ['wa','wo'],
            GA: ['ga','gi','gu','ge','go'],
            ZA: ['za','ji','zu','ze','zo'],
            DA: ['da',['dji', 'dzi', 'ji'],'dzu','de','do'],
            BA: ['ba','bi','bu','be','bo'],
            PA: ['pa','pi','pu','pe','po'],
            KYA: ['kya','kyu','kyo'],
            SHA: ['sha','shu','sho'],
            CHA: ['cha','chu','cho'],
            NYA: ['nya','nyu','nyo'],
            HYA: ['hya','hyu','hyo'],
            MYA: ['mya','myu','myo'],
            RYA: ['rya','ryu','ryo'],
            GYA: ['gya','gyu','gyo'],
            JA: ['ja','ju','jo'],
            DYA: ['dya','dyu','dyo'],
            BYA: ['bya','byu','byo'],
            PYA: ['pya','pyu','pyo'],
            VCH1: [
                'watashi', 'anata', 'kaishain', 'shain', 'shachou', 'buchou', 'kachou', 'otoko', 'onna', 'sensei',
                'gakusei', 'nihonjin', 'minna', 'minasan', 'tomodachi', 'hito', 'kata',
                'kazoku', 'kenshuusei', 'kaisha', 'gakkou', 'daigaku', 'uchi', 'ie', 'heya',
                'chuushajou', 'otearai', 'kuruma', 'hon', 'kuni', 'kotoba', 'san', 'namae',
            ],
            VCH2: [
                'byouin', 'koujou', 'ginkou', 'taishikan', 'toshokan', 'eigakan', 'kissaten', 'honya', 'kaigishitsu', 
                'ryou', 'eki', 'gaikokujin', 'ryoushin', 'kodomo', 'ko', 'inu', 'neko', 'kaban', 'keitai', 'denwa', 'kagi', 
                'megane', 'tokei', 'tsukue', 'hikidashi', 'isu', 'ki',
            ],
        },
    },
    Katakana: {
        KANA: {
            A: ['ア','イ','ウ','エ','オ'],
            KA: ['カ','キ','ク','ケ','コ'],
            SA: ['サ','シ','ス','セ','ソ'],
            TA: ['タ','チ','ツ','テ','ト'],
            NA: ['ナ','ニ','ヌ','ネ','ノ','ン'],
            HA: ['ハ','ヒ','フ','ヘ','ホ'],
            MA: ['マ','ミ','ム','メ','モ'],
            RA: ['ラ','リ','ル','レ','ロ'],
            YA: ['ヤ','ユ','ヨ'],
            WA: ['ワ','ヲ'],
            GA: ['ガ','ギ','グ','ゲ','ゴ'],
            ZA: ['ザ','ジ','ズ','ゼ','ゾ'],
            DA: ['ダ','ヂ','ヅ','デ','ド'],
            BA: ['バ','ビ','ブ','ベ','ボ'],
            PA: ['パ','ピ','プ','ペ','ポ'],
            KYA: ['キャ','キュ','キョ'],
            SHA: ['シャ','シュ','ショ'],
            CHA: ['チャ','チュ','チョ'],
            NYA: ['ニャ','ニュ','ニョ'],
            HYA: ['ヒャ','ヒュ','ヒョ'],
            MYA: ['ミャ','ミュ','ミョ'],
            RYA: ['リャ','リュ','リョ'],
            GYA: ['ギャ','ギュ','ギョ'],
            JA: ['ジャ','ジュ','ジョ'],
            DYA: ['ヂャ','ヂュ','ヂョ'],
            BYA: ['ビャ','ビュ','ビョ'],
            PYA: ['ピャ','ピュ','ピョ'],
            VCH1: [
                'アメリカ', 'フィリピン', 'エンジニア', 'オフィス', 'コンピュータ', 'パソコン', 'カメラ', 'ノート', 'スリッパ',
            ],
            VCH2: [
                'モール', 'カフェ', 'レストラン', 'デパート', 'スーパー', 'ビル', 'アパート', 'テーブル', 'テレビ', 'クラス',
            ],
        },
        ROMAJI: {
            A: ['a','i','u','e','o'],
            KA: ['ka','ki','ku','ke','ko'],
            SA: ['sa','shi','su','se','so'],
            TA: ['ta','chi','tsu','te','to'],
            NA: ['na','ni','nu','ne','no','n'],
            HA: ['ha','hi','fu','he','ho'],
            MA: ['ma','mi','mu','me','mo'],
            RA: ['ra','ri','ru','re','ro'],
            YA: ['ya','yu','yo'],
            WA: ['wa','wo'],
            GA: ['ga','gi','gu','ge','go'],
            ZA: ['za','ji','zu','ze','zo'],
            DA: ['da',['dji', 'dzi', 'ji'],'dzu','de','do'],
            BA: ['ba','bi','bu','be','bo'],
            PA: ['pa','pi','pu','pe','po'],
            KYA: ['kya','kyu','kyo'],
            SHA: ['sha','shu','sho'],
            CHA: ['cha','chu','cho'],
            NYA: ['nya','nyu','nyo'],
            HYA: ['hya','hyu','hyo'],
            MYA: ['mya','myu','myo'],
            RYA: ['rya','ryu','ryo'],
            GYA: ['gya','gyu','gyo'],
            JA: ['ja','ju','jo'],
            DYA: ['dya','dyu','dyo'],
            BYA: ['bya','byu','byo'],
            PYA: ['pya','pyu','pyo'],
            VCH1: [
                'amerika', 'firipin', 'enjinia', 'ofisu', ['konpyuta', 'konpyuuta'], 'pasokon', 'kamera', ['noto', 'nouto', 'nooto'], 'surippa',
            ],
            VCH2: [
                ['moru', 'mooru', 'mouru'], 'kafe', 'resutoran', ['depato', 'depaato'], ['supa', 'suupaa'], 'biru', ['apato', 'apaato',], 
                ['teburu', 'teiburu', 'teeburu'], 'terebi', 'kurasu',
            ],
        }
    }
}